# Generated by Django 3.1.7 on 2021-03-17 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210317_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='instragram_username',
            field=models.CharField(blank=True, default='dhj', max_length=255, null=True),
        ),
    ]
