# Generated by Django 3.1.7 on 2021-03-17 10:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210317_1553'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instragram_username',
            new_name='instragram_url',
        ),
    ]
