# Generated by Django 3.1.7 on 2021-03-17 11:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210317_1620'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='instragram_url',
            new_name='instagram_url',
        ),
    ]
